source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

gem "bootsnap", require: false
gem "rack-cors"

gem "image_processing", "~> 1.2"

group :development, :test do
  gem "dotenv-rails"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false

  gem "csv", "~> 3.3"
  gem "simplecov", "~> 0.22.0", require: false
  gem "rswag", "~> 2.17"
  gem "ostruct", "~> 0.6.3"
  gem "rspec-rails", "~> 8.0"
end
